github: [huzaifasad] # Replace with your GitHub username if you use GitHub Sponsors
patreon: huzaifasad # Replace with your Patreon username if you have one
open_collective: huzaifasad # Replace with your Open Collective username if you have one
ko_fi: huzaifasad # Replace with your Ko-fi username if you have one
buy_me_a_coffee: huzaifasad # Replace with your Buy Me a Coffee username
